import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "InfinityAR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html lang="en">
    <head>
      {/* ✅ Favicon (SVG only) */}
      <link rel="icon" href="/favicon.svg" type="image/svg+xml" />

      {/* ✅ Google Fonts preload + stylesheet */}
      <link
        rel="preload"
        as="style"
        href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700;900&family=Space+Grotesk:wght@400;500;700&display=swap"
      />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700;900&family=Space+Grotesk:wght@400;500;700&display=swap"
      />
    </head>

    <body
      className={`${geistSans?.variable ?? ""} ${geistMono?.variable ?? ""} antialiased`}
    >
      {children}
    </body>
  </html>
);

}

